# basic quantization settings
wbits: 2
group_size: 128
# training settings
cuda_ids: "3,7"
epochs: 2
net: Qwen2.5
batch_size: 2
quant_lr: 0.0001
weight_lr: 0.00001
off_load_to_disk: False
loss_func: MSE # "MSE", "FKLD" , "RKLD", "FKLD_RKLD" ,"MSE_FKLD", "MSE_RKLD", "MSE_FKLD_RKLD"
crossblock_window_size: 1
train_size: 4096
slide_step: 1

model: /home/ubuntu/data/exp/proj2410/model/Qwen2.5-0.5B
# save settings
output_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen-2.5-0.5B/EfficientQAT/w2gs128-fast-end2start-align-end/
log_loss: /home/ubuntu/data/exp/proj2410/quant_model/Qwen-2.5-0.5B/EfficientQAT/w2gs128-fast-end2start-align-end/loss.csv
save_quant_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen-2.5-0.5B/EfficientQAT/w2gs128-fast-end2start-align-end/
clamp_method: STE
train_shedule_type: end2start
align_type: end