# basic quantization settings
wbits: 3
group_size: 128
# training settings
cuda_ids: "0,1"
epochs: 2
net: Qwen2.5
batch_size: 2
quant_lr: 0.0001
weight_lr: 0.00001
off_load_to_disk: False
loss_func: MSE # "MSE", "FKLD" , "RKLD", "FKLD_RKLD" ,"MSE_FKLD", "MSE_RKLD", "MSE_FKLD_RKLD"
crossblock_window_size: 1
train_size: 4096
slide_step: 1

model: /home/ubuntu/data/exp/proj2410/quant_model/Qwen-2.5-0.5B/EfficientQAT/w4gs128-fake
# save settings
output_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen-2.5-0.5B/EfficientQAT/w3gs128-from-4bit/
log_loss: /home/ubuntu/data/exp/proj2410/quant_model/Qwen-2.5-0.5B/EfficientQAT/w3gs128-from-4bit/loss.csv
save_quant_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen-2.5-0.5B/EfficientQAT/w3gs128-from-4bit/
clamp_method: STE

align_type: tail