# basic quantization settings
wbits: 2
group_size: 128
# training settings
cuda_ids: "2,3"
epochs: 5
net: Llama2-7b
batch_size: 2
quant_lr: 0.0001
weight_lr: 0.00001
off_load_to_disk: False
loss_func: MSE # "MSE", "FKLD" , "RKLD", "FKLD_RKLD" ,"MSE_FKLD", "MSE_RKLD", "MSE_FKLD_RKLD"
crossblock_window_size: 1
train_size:  4096
slide_step: 1
clip_grad: 0.3


model: /home/ubuntu/data/exp/proj2410/model/Llama2-7b
# save settings
output_dir: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/w2gs128/
log_loss: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/w2gs128/loss.csv
save_quant_dir: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/w2gs128/
clamp_method: STE

align_type: tail