cluster_settings:
  cuda_ids:
  - 3
model_settings:
  net: Llama2-7b
  model: /home/ubuntu/data/exp/proj2410/model/Llama2-7b
  save_parent_dir: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B
hyperparam_settings:
  wbits: 2
  group_size: 128
  method_name: gradualquant
  min_lr_factor: 20
  clamp_method: STE
  align_type: tail
  crossblock_window_size: 1
  slide_step: 1
  gradual_quant: True
  gradual_factor: 4.0
train_param_settings:
  cache_dir: /home/ubuntu/data/exp/proj2410/cache
  output_dir: ./log/
  save_quant_dir: None
  real_quant: true
  resume_quant: None
  calib_dataset: c4
  train_size: 4096
  val_size: 64
  training_seqlen: 2048
  batch_size: 4
  epochs: 2
  ppl_seqlen: 2048
  seed: 42
  eval_ppl: true
  eval_tasks: piqa
  eval_batch_size: 16
  quant_lr: 0.0001
  weight_lr: 4.0e-05
  clip_grad: 1
  wd: 0
  max_memory: 70GiB
  early_stop: 0
  off_load_to_disk: false
  log_loss: None
  loss_func: MSE
  clamp_method: STE
  quant_shedule_type: partial
  train_shedule_type: start2end
  with_catcher: false
  quant_method: block_ap
method: gradualquant
save_dir: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/progqw2bit_cali_c4/
output_dir: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/progqw2bit_cali_c4/
log_loss: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/progqw2bit_cali_c4/loss.csv
