# basic quantization settings
wbits: 2
group_size: 128
# training settings
cuda_ids: "0,1"
epochs: 4
rank: 4
world_size: 4
min_lr_factor: 20
net: Qwen2.5-7B
batch_size: 2
quant_lr: 0.001
weight_lr: 0.0001
off_load_to_disk: False
loss_func: MSE # "MSE", "FKLD" , "RKLD", "FKLD_RKLD" ,"MSE_FKLD", "MSE_RKLD", "MSE_FKLD_RKLD"
crossblock_window_size: 1
train_size:  4096
slide_step: 1
clip_grad: 1
dampen_loss: True


model: /home/ubuntu/data/exp/proj2410/model/Qwen2.5-7B
# save settings
output_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-7B/EfficientQAT/w2gs128-dampenloss/
log_loss: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-7B/EfficientQAT/w2gs128-dampenloss/loss.csv
save_quant_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-7B/EfficientQAT/w2gs128-dampenloss/
clamp_method: STE

align_type: tail