_train_steps:
    value: 205
_wandb:
    value:
        cli_version: 0.23.1
        e:
            7t6qjikz6anlqq986xhfvnjkqvh9nyha:
                args:
                    - ./VeOmni/configs/pretrain/llama2.yaml
                codePath: VeOmni/tasks/quantize/train.py
                codePathLocal: VeOmni/tasks/quantize/train.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "169410297856"
                        used: "36647993344"
                email: heqi2019001@gmail.com
                executable: /home/ubuntu/data/exp/proj2410/EfficientQAT/.venv/bin/python3
                git:
                    commit: bf03f95d65a8986ef9e142ff829bc9226ca6f9d6
                    remote: git@github.com:hq-ansel/proj2410.git
                gpu: NVIDIA RTX A6000
                gpu_count: 3
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-6523522d-9af2-2003-0da6-fbb4d8ee3f08
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX A6000
                      uuid: GPU-01797ecd-0d32-bb00-04f4-d81788372162
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-f7b88c93-dacd-78e5-692c-67a80bb35a64
                host: heqi
                memory:
                    total: "540657156096"
                os: Linux-5.15.0-67-generic-x86_64-with-glibc2.31
                program: /home/ubuntu/data/exp/proj2410/./VeOmni/tasks/quantize/train.py
                python: CPython 3.12.9
                root: /home/ubuntu/data/exp/proj2410
                startedAt: "2025-12-03T12:59:06.992081Z"
                writerId: 7t6qjikz6anlqq986xhfvnjkqvh9nyha
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 83
                - 98
                - 105
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 83
                - 98
                - 105
            "3":
                - 13
                - 16
            "4": 3.12.9
            "5": 0.23.1
            "6": 4.57.1
            "12": 0.23.1
            "13": linux-x86_64
activation_gpu_limit:
    value: 0
allow_cuda_launch_blocking:
    value: false
attn_implementation:
    value: flash_attention_2
basic_modules:
    value: []
broadcast_model_weights_from_rank0:
    value: true
bsz_warmup_init_mbtoken:
    value: 200
bsz_warmup_ratio:
    value: 0.007
chat_template:
    value: default
ckpt_manager:
    value: dcp
config_path:
    value: /home/ubuntu/data/exp/proj2410/model/Llama2-7b
context_parallel_size:
    value: 1
data_parallel_mode:
    value: fsdp2
data_parallel_replicate_size:
    value: 1
data_parallel_shard_size:
    value: 3
data_parallel_size:
    value: 3
data_tag:
    value: default
data_type:
    value: plaintext
dataloader_batch_size:
    value: 1
dataloader_type:
    value: native
datasets_type:
    value: mapping
drop_last:
    value: true
drop_resume_buffer:
    value: false
dyn_bsz:
    value: true
dyn_bsz_buffer_size:
    value: 200
dyn_bsz_margin:
    value: 0
dyn_bsz_runtime:
    value: worker
empty_cache_steps:
    value: 500
enable_activation_offload:
    value: false
enable_compile:
    value: false
enable_forward_prefetch:
    value: true
enable_fsdp_offload:
    value: false
enable_full_determinism:
    value: false
enable_full_shard:
    value: true
enable_gradient_checkpointing:
    value: true
enable_mixed_precision:
    value: true
enable_multisource:
    value: false
enable_profiling:
    value: false
enable_rank0_init:
    value: false
enable_reentrant:
    value: false
encode_target:
    value: false
ep_outside:
    value: false
expert_parallel_size:
    value: 1
force_use_huggingface:
    value: false
gc_steps:
    value: 500
global_batch_size:
    value: 12
global_rank:
    value: 0
gradient_accumulation_steps:
    value: 4
image_keys:
    value: images
init_device:
    value: meta
input_encoder:
    value: encoder
load_checkpoint_path:
    value: ""
local_rank:
    value: 0
lr:
    value: 0.0003
lr_decay_ratio:
    value: 1
lr_decay_style:
    value: constant
lr_min:
    value: 1e-07
lr_start:
    value: 0
lr_warmup_ratio:
    value: 0.007
max_grad_norm:
    value: 1
max_seq_len:
    value: 4096
max_steps:
    value: null
micro_batch_size:
    value: 1
model_assets_dir:
    value: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/test/model_assets
model_path:
    value: /home/ubuntu/data/exp/proj2410/model/Llama2-7b
moe_implementation:
    value: null
no_decay_modules:
    value: []
no_decay_params:
    value: []
num_train_epochs:
    value: 2
num_workers:
    value: 2
optimizer:
    value: adamw
output_dir:
    value: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/test
output_encoder:
    value: decoder
pin_memory:
    value: true
pipeline_parallel_size:
    value: 1
predownload_factor:
    value: 0.5
prefetch_factor:
    value: 2
profile_end_step:
    value: 2
profile_profile_memory:
    value: true
profile_rank0_only:
    value: true
profile_record_shapes:
    value: true
profile_start_step:
    value: 1
profile_this_rank:
    value: false
profile_trace_dir:
    value: ./trace
profile_with_stack:
    value: true
rmpad:
    value: false
rmpad_with_pos_ids:
    value: true
save_async:
    value: false
save_checkpoint_path:
    value: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/test/checkpoints
save_epochs:
    value: 1
save_hf_weights:
    value: true
save_steps:
    value: 100
seed:
    value: 42
shuffle_shard_nums:
    value: 1
silent_exception:
    value: false
source_name:
    value: null
split_nums:
    value: 1
step2token_path:
    value: /home/ubuntu/data/exp/proj2410/quant_model/Llama2-7B/EfficientQAT/test/step2token.json
tensor_parallel_size:
    value: 1
text_keys:
    value: text
tokenizer_path:
    value: /home/ubuntu/data/exp/proj2410/model/Llama2-7b
train_path:
    value: /home/ubuntu/data/exp/proj2410/hf_home/rp_text_caches/redpajama_text_ns1024_sl4096_seed42_train/data-00000-of-00001.arrow
train_size:
    value: 10000000
ulysses_parallel_size:
    value: 1
use_wandb:
    value: true
wandb_name:
    value: Meta-Llama-2-7B-TEST
wandb_project:
    value: Meta-Llama-2-7B
weight_decay:
    value: 0.01
world_size:
    value: 3
