cluster_settings:
  cuda_ids:
  - 2
model_settings:
  net: Qwen2.5-14B
  model: /home/ubuntu/data/exp/proj2410/model/Qwen2.5-14B
  save_parent_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-14B
hyperparam_settings:
  wbits: 2
  group_size: 128
  method_name: w2g128
  min_lr_factor: 20
  clamp_method: STE
  align_type: tail
  crossblock_window_size: 1
  slide_step: 1
train_param_settings:
  cache_dir: /home/ubuntu/data/exp/proj2410/cache
  output_dir: ./log/
  save_quant_dir: None
  real_quant: true
  resume_quant: None
  calib_dataset: wikitext2
  train_size: 4096
  val_size: 64
  training_seqlen: 2048
  batch_size: 2
  epochs: 2
  ppl_seqlen: 2048
  seed: 42
  eval_ppl: false
  eval_tasks: piqa
  eval_batch_size: 16
  quant_lr: 0.0001
  weight_lr: 1.0e-05
  clip_grad: 1
  wd: 0
  max_memory: 70GiB
  early_stop: 0
  off_load_to_disk: false
  log_loss: None
  loss_func: MSE
  clamp_method: STE
  quant_shedule_type: partial
  train_shedule_type: start2end
  with_catcher: false
  quant_method: block_ap
method: w2g128
save_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-14B/EfficientQAT/w2g128/
output_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-14B/EfficientQAT/w2g128/
log_loss: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-14B/EfficientQAT/w2g128/loss.csv
