# basic quantization settings
wbits: 2
group_size: 128
# training settings
cuda_ids: "5,6"
epochs: 5
net: Qwen2.5-32B
batch_size: 2
quant_lr: 0.0001
weight_lr: 0.00005
off_load_to_disk: False
loss_func: MSE # "MSE", "FKLD" , "RKLD", "FKLD_RKLD" ,"MSE_FKLD", "MSE_RKLD", "MSE_FKLD_RKLD"
crossblock_window_size: 1
train_size:  4096
slide_step: 1
clip_grad: 9999
sub_space_grad_clean: True

model: /home/ubuntu/data/exp/proj2410/model/Qwen2.5-32B
# save settings
output_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-32B/EfficientQAT/w2gs128-subspace-lr1/
log_loss: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-32B/EfficientQAT/w2gs128-subspace-lr1/loss.csv
save_quant_dir: /home/ubuntu/data/exp/proj2410/quant_model/Qwen2.5-32B/EfficientQAT/w2gs128-subspace-lr1/
clamp_method: STE

align_type: tail